### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by kaushikCanada** [Azure-Samples/video-analyzer-iot-edge-csharp#15]
1. I have setup LVA edge and doing video analysis . I want to do spatial analysis. Currently i have been using a jetson nano. However i have a feeling these are better suited for amd64 type stuff. What kind of edge hardware do you recommend for spatial analysis and all that?
2. [concepts](https://docs.microsoft.com/en-us/azure/azure-video-analyzer/video-analyzer-docs/overview) does not open up a document. could you please give any videos on running this?

**Comment by naiteeks** [comment]
hi @kaushikCanada  - Spatial Analysis is optimized to work on devices that have NVIDIA GPUs only. So, compatible hardware would be:
1. Azure Stack Edge with NVIDIA T4 GPU
2. Azure VM with NVIDIA GPU
3. Any Desktop with NVIDIA GPU (Tensor Core T4 and K80)

Supported documentation will be going live on May 25th. I will share the link here once it is live.

**Comment by naiteeks** [comment]
Hi @kaushikCanada  - here is the link to the tutorial on how to use AVA with Spatial Analysis container.
https://docs.microsoft.com/en-us/azure/azure-video-analyzer/video-analyzer-docs/computer-vision-for-spatial-analysis?tabs=azure-stack-edge

Note that you will need a NVIDIA GPU for SA container to work.

**Comment by kaushikCanada** [comment]
Hi naiteek,

Thank you for your reply. Really appreciate it. I have been able to run the
graphs and topologies on the nvidia jetson. However i think most of the co
tIners are not that arm64 friendly so im arranging for an intel nuc. One
question i have is this - does the spatial analysis container really need
so much resources? What happens if we run it on 4 gb gpu instead. Also is
the spatial analysis deployment for desktol different from edge in some way?

Hehe thank you i am having a lot of fun doing this. I am eagerly waiting
for my intel mini box with nv 1650 to try the azure video analyzer. What do
you think? Is tha decent edge to work with all theze things?

**Comment by naiteeks** [comment]
The Spatial Analysis container as of today is customized and designed to work with NVIDIA GPUs today (specifically Tensor T4 and NVIDIA K80).

Alternatively, you can even try out the Intel OpenVino models. If you are using Intel devices, some examples on how to use is here: 
https://docs.microsoft.com/en-us/azure/azure-video-analyzer/video-analyzer-docs/use-intel-openvino-tutorial
https://docs.microsoft.com/en-us/azure/azure-video-analyzer/video-analyzer-docs/use-intel-grpc-video-analytics-serving-tutorial

**Comment by naiteeks** [comment]
Closing issue as the comments have addressed the concerns. @kaushikCanada  - please feel free to let us know if there are any more questions.
